### ISSUE TITLE
[BUG] Nothing shown after cloning a repository

### ISSUE THREAD

**Issue by BenEngbers** [francescmm/GitQlient#258] opened 2022-11-04 17:11 UTC
**Describe the bug**
After cloning a repo from github a status-bar pops up indicating that a repository is loaded. Locally a directory for the clone is created but nothing happens

**To Reproduce**
1. start gitqlient
2. clone a repo

**Expected behavior**
I would expect to see a tree-view from the master

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Fedora 36
 - Release version or SHA: 1.5.0
 - If manually compiled, compiler version: 

**Additional context**

**Comment by francescmm** [comment] 2022-11-07 06:59
Hi @BenEngbers, could you attach a screenshot of the issue?

Take into account that if the repository has no commits yet, it won't show antything. You will have to commit at least once to see the treeview.

**Comment by francescmm** [comment] 2022-11-07 07:12
Also, I've checked in the case of a cloned empty repo, and since there are no commits, the branch master cannot point to any SHA and therefore is not shown. Unfortunately for the GUI, this is how Git actually works.

**Comment by BenEngbers** [comment] 2022-11-10 11:42
Sorry for the delay, I have been away a few days.

After a reboot, I have tried to clone a client for basex (https://github.com/JohnLeM/BasexCPPAPI.git).
In the gitqlient I have entered ~/Git as destination directory, copied https://github.com/JohnLeM/BasexCPPAPI.git to URL and entered my Github username and email. After clicking accept in the dialog, I get this popup:
![Schermafdruk van 2022-11-10 12-34-57](https://user-images.githubusercontent.com/12139617/201081182-00d1920a-1448-47cb-88ae-0b58ceaddf20.png)
and then nothing happens.

My personal github-page shows that I am logged in.

Ben

**Comment by francescmm** [comment] 2022-11-11 08:13
I'll take a look through that screen. I realize now that I've tested it locally but with master, so it might be that I already fixed this hehe.

I'll checkout 1.5.0 to see that I can reproduce it and then double-check **master** :smile: 

Thanks for the report!

**Comment by francescmm** [comment] 2022-12-03 18:00
@BenEngbers I finally had time to dig into this. I found the issue and I'm right now fixing it :)

**Comment by francescmm** [comment] 2022-12-03 18:19
I'll prepare a new release with all the changes so far.

**Closed by francescmm** 2022-12-03 18:19 UTC
Labels: Bug
